[package]
name = "bq34z100_rust"
description = "Provides an embedded_hal driver for the fuel gauge series bq34z100"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause-No-Military-License"
repository = "https://github.com/empirephoenix/bq34z100_rust"
keywords = ["battery", "fuel gauge", "bq34z100", "embedded-hal-driver"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "1.0.0"